[build]
  base    = "."
  publish = "./dist/"
  environment = {NODE_VERSION = "16.16.0" }

# Set enviroment variable prompts for templates
[template.environment]
  DAILY_API_KEY = "Your Daily API key"